pygments: true
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title: AEON Sunnies
theme: basic
#
# 1. Your website ( could be same as this page - see below )
website: http://igg.me/at/AEON
#
# 2. URL of this page
url: http://aeonattire.github.io/
#
# 3. About your kickstarter project
project: This project is to bring some awesome gloves to to people
  #
  # Name of the project
  name: AEON Touchpoint Gloves
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url: http://goo.gl/o9cmk  
  # URL of a cover photo of your project
  cover_image: http://www.aeonattire.com/wp-content/uploads/2013/11/test_000001.png
  
  #
  # Use a one-liner to describe your project
  description: AEON Attire-- Finally Leather Gloves as Smart as your Phone
#
# 4. Your Twitter handle
twitter_handle: AEONAttire
#
# 5. Your Google analytics ID (Optional)
google_analytics: 34283077-1
#
# 6. Welcome text, add <br /> to break lines
welcome_text: |
-  We hope you're having an awesome day. You're here because we know you have influence. <br />
-  When you share something, people pay attention. <br />
-  So, please take a few seconds to spread the AEON love.♥ <br />
-  Thanks so much from Patrick, Wei, Wei and the entire AEON Team  ♥ 


